import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "@/components/site/header"; import { Footer } from "@/components/site/footer"; import { CtaBand } from "@/components/site/cta-band"; import { PhonePreview } from "@/components/product/phone-preview"; import { FeatureIcon } from "@/components/product/feature-icon";
import { getContent,isLocale } from "@/lib/content";
import { ArrowUpRight } from "lucide-react";
import { Reveal } from "@/components/site/reveal";
import { ProductExplorer } from "@/components/product/product-explorer";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;return{title:locale==="or"?"ଓଡ଼ିଆରୁ ଆତ୍ମବିଶ୍ୱାସରେ ଇଂରାଜୀ":"Speak English with confidence—starting in Odia",alternates:{canonical:`/${locale}`,languages:{en:"/en",or:"/or"}}};}
export default async function Home({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();const c=getContent(locale),h=c.home,p=`/${locale}`;return <><a href="#main" className="hidden-field">Skip to content</a><Header locale={locale} page="home" nav={c.nav}/><main id="main" className={locale==="or"?"odia":""}>
<section className="hero"><div className="hero-edition">E—T / 01</div><div className="shell hero-grid"><Reveal className="hero-copy"><span className="eyebrow">{h.eyebrow}</span><h1 className="heading display">{h.title}<span className="gradient-text"> {h.accent}</span></h1><p className="lead">{h.body}</p><div className="hero-actions"><Link className="button button-primary" href="#waitlist">{c.nav.cta}<ArrowUpRight/></Link><Link className="button button-secondary" href={`${p}/product`}>{h.secondary}</Link></div><p className="microcopy">{h.note}</p><div className="proof-strip">{h.proof.map((x,i)=><span className="proof-chip" key={x}><i>0{i+1}</i>{x}</span>)}</div></Reveal><Reveal delay={.12}><PhonePreview label={locale==="en"?"Concept preview":"ଧାରଣା ପ୍ରିଭ୍ୟୁ"}/></Reveal></div><div className="hero-marquee" aria-hidden><span>VOICE</span><i/> <span>CONFIDENCE</span><i/> <span>OPPORTUNITY</span></div></section>
<section className="trust"><div className="shell trust-grid">{h.trust.map(([a,b])=><div className="trust-item" key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></section>
<ProductExplorer/>
<section className="section benefits-section"><div className="shell"><div className="section-intro"><span className="eyebrow">WHY E-TALK</span><h2 className="section-title display">{h.benefitsTitle}</h2><p className="lead">{h.benefitsBody}</p></div><div className="benefits-grid">{h.benefits.map(([,a,b],index)=><article className="benefit" key={a}><div className="icon"><FeatureIcon index={index}/></div><span className="benefit-index">0{index+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
<section className="section blue-section" id="how"><div className="shell"><span className="eyebrow" style={{color:"var(--lime)"}}>HOW IT WORKS</span><h2 className="section-title display">{h.stepsTitle}</h2><p className="lead">{h.stepsBody}</p><div className="grid-3 etalk-steps">{h.steps.map(([n,a,b])=><article className="etalk-step" key={n}><span className="step-number">{n}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
<section className="learning-proof"><div className="shell learning-proof-grid"><Reveal><div className="proof-visual"><div className="proof-visual-head"><span>LEARNING PATH</span><span>64% COMPLETE</span></div><h3>Interview confidence</h3><div className="curriculum-line"><i className="complete"/><i className="complete"/><i className="active"/><i/><i/></div><div className="curriculum-items"><span>Foundations</span><span>Clear answers</span><span>Mock interview</span></div><div className="feedback-note"><span>AI</span><p><strong>Coach insight</strong>Your answers are clear. Next, practise giving specific examples.</p></div></div></Reveal><Reveal delay={.08}><div className="proof-copy"><span className="eyebrow">MEASURABLE PROGRESS</span><h2 className="section-title display">Not more content.<br/>Better learning.</h2><p className="lead">Every lesson connects to a goal, every practice gives useful feedback, and every week makes progress visible.</p><div className="proof-metrics"><div><strong>15</strong><span>minutes a day</span></div><div><strong>1:1</strong><span>AI feedback</span></div><div><strong>B1</strong><span>current level</span></div></div></div></Reveal></div></section>
<section className="section audience-section"><div className="shell audience-layout"><div className="audience-sticky"><span className="eyebrow">BUILT AROUND REAL LIFE</span><h2 className="section-title display">{h.audienceTitle}</h2><p>Not one generic course. A practical English path shaped around where you need your voice next.</p></div><div className="audience-list">{h.audience.map(([a,b],i)=><Reveal key={a}><article className="audience-row"><span>0{i+1}</span><div><h3>{a}</h3><p>{b}</p></div><ArrowUpRight/></article></Reveal>)}</div></div></section>
<section className="section faq-section"><div className="shell faq-layout"><div><span className="eyebrow">FAQ</span><h2 className="section-title display">{h.faqTitle}</h2></div><div className="faq-list">{h.faq.map(([q,a],i)=><details key={q}><summary><span>0{i+1}</span>{q}</summary><p>{a}</p></details>)}</div></div></section><CtaBand locale={locale} form={c.form} sourcePage="home"/></main><Footer locale={locale} nav={c.nav}/><Link className="button button-primary mobile-cta" href="#waitlist">{c.nav.cta}</Link></>}
