"use client";
import * as Tabs from "@radix-ui/react-tabs";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { AudioLines, Languages, TrendingUp, Mic, Sparkles, Check, ArrowUpRight, Home, Map, UserRound, Flame } from "lucide-react";
import { useState } from "react";

const modes=[
  {id:"speak",label:"Speak",Icon:AudioLines,kicker:"REAL-TIME SPEECH COACH",title:"Say it. See exactly how to improve it.",body:"Practise without an audience. E-Talk listens for clarity, pace, and pronunciation—then gives you one useful next step.",stat:"92",statLabel:"clarity score"},
  {id:"understand",label:"Understand",Icon:Languages,kicker:"ODIA-SUPPORTED CLARITY",title:"Understand the thought before memorising the phrase.",body:"Reveal contextual Odia guidance only when you need it, then return to English practice without breaking your flow.",stat:"2×",statLabel:"language context"},
  {id:"progress",label:"Progress",Icon:TrendingUp,kicker:"A PATH THAT RESPONDS",title:"Know what changed—and what comes next.",body:"Your route adapts around strengths and weak spots, turning daily practice into visible, motivating progress.",stat:"B1",statLabel:"current pathway"},
] as const;

function AppNav({active}:{active:number}){return <div className="sim-nav">{[Home,Mic,Map,UserRound].map((Icon,i)=><span className={active===i?"active":""} key={i}><Icon/></span>)}</div>}
function Device({children,active=1}:{children:React.ReactNode;active?:number}){return <div className="sim-device"><div className="sim-island"/><div className="sim-status"><span>9:41</span><span>● ◒</span></div><div className="sim-screen">{children}</div><AppNav active={active}/></div>}
function SpeakVisual(){return <Device><div className="sim-head"><span className="sim-badge"><Sparkles/> AI COACH</span><span className="sim-online"><i/> LIVE</span></div><div className="sim-orb"><motion.span animate={{scale:[1,1.2,1],opacity:[.7,.15,.7]}} transition={{duration:2,repeat:Infinity}}/><Mic/></div><p className="sim-listening">LISTENING</p><div className="sim-user-bubble">I am preparing for my first interview.</div><div className="sim-wave">{[20,35,55,30,67,42,78,50,38,60,29,47].map((h,i)=><motion.i key={i} animate={{height:[h,h*.5,h]}} transition={{duration:.85,repeat:Infinity,delay:i*.04}}/>)}</div><div className="sim-coach"><span>AI</span><p><small>COACH INSIGHT</small>Soften the pause after “preparing”.</p></div></Device>}
function UnderstandVisual(){const [reveal,setReveal]=useState(false);return <Device><div className="sim-head"><span className="sim-badge"><Languages/> CONTEXT MODE</span><span>04 / 12</span></div><h4 className="sim-question">What does this<br/>phrase really mean?</h4><button className={`sim-flip ${reveal?"revealed":""}`} onClick={()=>setReveal(!reveal)} aria-pressed={reveal}><AnimatePresence mode="wait"><motion.div key={reveal?"or":"en"} initial={{rotateX:70,opacity:0}} animate={{rotateX:0,opacity:1}} exit={{rotateX:-70,opacity:0}}><small>{reveal?"ଓଡ଼ିଆରେ ଅର୍ଥ":"ENGLISH PHRASE"}</small><strong>{reveal?"ଆପଣ ମୋତେ ଏହା ବୁଝାଇ ପାରିବେ କି?":"Could you walk me through it?"}</strong><span>{reveal?"Tap to see English":"Tap for Odia meaning"} <ArrowUpRight/></span></motion.div></AnimatePresence></button><div className="sim-context"><Check/><p><strong>Polite request</strong><small>Useful in workplace conversations</small></p></div></Device>}
function ProgressVisual(){return <Device active={2}><div className="sim-head"><span className="sim-badge"><Map/> YOUR PATH</span><span><Flame/> 7</span></div><div className="sim-progress-top"><div className="sim-ring" style={{"--progress":"64%"} as React.CSSProperties}><span>64%</span></div><div><small>INTERVIEW CONFIDENCE</small><strong>B1 · Intermediate</strong><span>8 of 14 lessons</span></div></div><div className="sim-path">{[["Start with clarity",1],["Structure your answer",1],["Sound natural",2],["Mock interview",0]].map(([title,state],i)=><motion.div initial={{opacity:0,x:-15}} animate={{opacity:1,x:0}} transition={{delay:i*.08}} className={`sim-path-row state-${state}`} key={title}><i>{state===1?<Check/>:i+1}</i><span>{title}</span>{state===2&&<em>NOW</em>}</motion.div>)}</div><div className="sim-week"><TrendingUp/><p><small>THIS WEEK</small><strong>Pronunciation improved 18%</strong></p></div></Device>}

export function ProductExplorer(){const [active,setActive]=useState("speak");const reduced=useReducedMotion();const mode=modes.find(x=>x.id===active)??modes[0];return <section className="product-explorer"><div className="explorer-aurora"/><div className="shell"><div className="explorer-heading"><div><span className="eyebrow">EXPLORE THE EXPERIENCE</span><h2 className="section-title display">Don’t imagine the app.<br/>Step inside it.</h2></div><p>Choose a learning moment and see how E‑Talk turns uncertainty into a clear next action.</p></div><Tabs.Root value={active} onValueChange={setActive} className="explorer-root"><Tabs.List className="explorer-tabs" aria-label="Explore E-Talk features">{modes.map(({id,label,Icon},i)=><Tabs.Trigger value={id} key={id}><span>0{i+1}</span><Icon/>{label}<ArrowUpRight/></Tabs.Trigger>)}</Tabs.List><div className="explorer-stage"><div className="explorer-copy"><AnimatePresence mode="wait"><motion.div key={mode.id} initial={reduced?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} transition={{duration:.4}}><span className="explorer-kicker">{mode.kicker}</span><h3>{mode.title}</h3><p>{mode.body}</p><div className="explorer-stat"><strong>{mode.stat}</strong><span>{mode.statLabel}</span></div></motion.div></AnimatePresence></div><div className="explorer-visual"><div className="sim-beam beam-one"/><div className="sim-beam beam-two"/><AnimatePresence mode="wait"><motion.div key={active} initial={reduced?false:{opacity:0,y:30,rotateY:-5}} animate={{opacity:1,y:0,rotateY:0}} exit={{opacity:0,y:-15}} transition={{duration:.55,ease:[.22,1,.36,1]}}>{active==="speak"?<SpeakVisual/>:active==="understand"?<UnderstandVisual/>:<ProgressVisual/>}</motion.div></AnimatePresence></div></div></Tabs.Root></div></section>}
